# Generated by Django 2.2.6 on 2020-03-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200310_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=90)),
                ('location', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=250, null=True)),
                ('category', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=30)),
            ],
        ),
    ]
